---
  version: 1.0

  platform: mingw64

  msys2-version: ">3.6.5"

  steps:
    - name: "#1"
      description: "Add requirements for building WebAssemby."
      packages:

    - name: '#2'
      description: "Update MSYS2 packages database (sync)"
      commands:
        - "sh -c 'pacman -Suu --noconfirm'"